### ISSUE TITLE
Emergency Kits - Functions implementation

### ISSUE THREAD

**Issue by codingbandit** [HTBox/TwoWeeksReady#12]
Dependent on issue #11 Modeling emergency kits

(Models available in [Wiki](https://github.com/HTBox/TwoWeeksReady/wiki/Emergency-Kits---Default-content))

For each of the functions below, we will be obtaining the user information from the authentication token. 

Encapsulate function signature parameters in classes.

Function names, signatures, object names, and number of functions are not set in stone:

GetBaseKits() returns BaseKit[]
GetKits() returns Kit[] -> /api/emergencykits
GetKit(KitId) returns Kit[]
CreateKit(Kit) returns Kit -> /api/emergencykits-create
CreateFromBaseKit(BaseKitId, Kit, count, unit) returns Kit -> /api/emergencykits-create-from-base-kit
UpdateKit(Kit) returns Kit
DeleteKit(KitId) returns bool

Once complete, please document the final API/Classes in the [Wiki](https://github.com/HTBox/TwoWeeksReady/wiki)

**Comment by codingbandit** [comment]
@schuback - when we create a kit off of a base kit, do we create a separate kit for the pets vs the people or are the contents of the base kit + pet kit combined into a single kit ?

**Comment by schuback** [comment]
I would say keep the pet kit separate.  Someone might have two pet kits (one for each pet - cat & dog, dog 1 and dog 2, or cat 1 and cat 2, etc). The same could apply for human kits - one for me, one for mom, one for kid 1, kid 2, etc. Make sense? @codingbandit

**Comment by schuback** [comment]
Home Kit
Pet Kit
Vehicle Kit
Go Kit

**Comment by schuback** [comment]
Sorry @codingbandit - I hit the wrong button when commenting.  :(

**Comment by codingbandit** [comment]
Wiki updated with API documentation
