### ISSUE TITLE
Configure Dev Containers

### ISSUE THREAD

**Issue by dpaquette** [HTBox/TwoWeeksReady#124]
To develop the full Client App, API and Admin app locally, we require a variety of SDKs to be installed and emulators to be running.

Investigate the feasibility of configuring dev containers reduce the effort required to get started as a new contributor. Could this also be configured to work with Code Spaces?

Off the top of my head, some of the dependencies are:
- Node / NPM
- Cosmos DB Emulator
- Azure Functions SDK
- Azure Storage Emulator
- .NET 5

**Comment by c0g1t8** [comment]
I've been using a single dockerfile to validate the build and development documentation.  The configuration should almost be identical for Codespaces.

I can share that later on today.
