### ISSUE TITLE
Documentation on how to use Dev Containers / Codespaces

### ISSUE THREAD

**Issue by dpaquette** [HTBox/TwoWeeksReady#127]
Provide some documentation and maybe a link to an intro video showing folks how to get started using dev containers and/or code spaces.

**Comment by dpaquette** [comment]
Paging @davidwesst  :-)

**Comment by codingbandit** [comment]
@davidwesst is assigned this issue (assigning myself to avoid parallel work)

**Comment by davidwesst** [comment]
I've uploaded a video to my YouTube channel: https://www.youtube.com/watch?v=rYfsNBODfZc

It's currently unlisted-- but feel free to share it. I'm going to publish it as part of my regular video feed in a couple of weeks.

Take a look and let me know if this is enough for the issue.

**Comment by dpaquette** [comment]
This is great @davidwesst! Can you add a link to your video in the README and we can get this issue closed?

**Comment by davidwesst** [comment]
I will do that ASAP and it shall be done.

**Comment by davidwesst** [comment]
@dpaquette PR created and assigned to you for review.
