### ISSUE TITLE
Emergency Kits - UI implementation

### ISSUE THREAD

**Issue by codingbandit** [HTBox/TwoWeeksReady#13]
Emergency Kits needs to be a section on the Preparedness tab/screen. 
1) Each Kit shall be identified with an icon or an image (Icons will be provided for each type of kit)
![image](https://user-images.githubusercontent.com/3979478/101661759-abbe5080-3a16-11eb-9e5a-888e2c1a4222.png)

Emergency kit listing
1) The emergency kit calculator provides the ability for the user to create a new list. (brings user to Emergency kit details)
2) The emergency kit list displays all kits created by the user. 
3) A search textbox is available for the user to filter the list.
4) Selecting a kit from the list will open the Emergency kit details screen (below)

![image](https://user-images.githubusercontent.com/3979478/101661046-d065f880-3a15-11eb-84e7-90ede0c8ba42.png)

Emergency kit details 
The flow for the creation/update of a kit and adding/removing kit items is not wireframed. (We will need clarification on this).
1) Selection of the kit type (on creation only) - select from base kits
2) Population of the starter list based on kit selected (on creation only)
3) Ability to create a kit from scratch (name, color, icon)
3) Displays a list of Kit Items
4) Allow for user to check the item as being available in the kit
5) Provides a way to to add items (see Emergency kit item details below)
6) Ability to update kit (name, color, icon)
7) Ability to delete kit
?) Should we provide a way to bulk delete items

Emergency kit item details
1) Create/Update form for kit items (Name, description, photo, expiry date, available in kit [bool])
2) Delete item from kit (returns to Emergency Kit details)

API documentation is available [in the Wiki](https://github.com/HTBox/TwoWeeksReady/wiki/Emergency-Kits---Default-content#api).

**Comment by MaximilianDixon** [comment]
We will provide an icon for each of the 4 types of kits: home, work, vehicle, and go-bag. This should make them easier to distinguish. I like emergency kit creation flow you developed. For deleting kits, I am open to any ideas as to how to make it intuitive. We should include an “are you sure you want to delete this” step to keep people from accidentally deleting something. Thoughts?

**Comment by codingbandit** [comment]
I agree with you having the warning before we delete something (I have unexpectedly deleted things by accident many times!). I would think it would be best shown on the Emergency Kit Details screen.

**Comment by MaximilianDixon** [comment]
Sounds good to me.

Maximilian Dixon, MUP, MIPM, CEM®
Hazards and Outreach Program Supervisor
(253) 512-7017<tel:(253)%20512-7017>
Office Hours: Mon-Thu 0730-1800<tel:0730-1800>

**Comment by MaximilianDixon** [comment]
Lists of the “minimum” supplies for their respective kits for 1 person or 1 pet:
 
Home Kit (2 Weeks Ready kit)
• Water, 14 gallons
• Water filtration (filter, purification tablets)
• Food, 2 weeks’ worth
• Set of clothing, 5
• Jacket
• Hat and gloves
• Poncho
• Sturdy shoes
• Blanket
• Light source (flashlight, headlamp)
• Extra batteries
• NOAA Weather radio
• Phone charger
• Multi-tool with knife and can opener
• Duct tape
• Crowbar
• Cash, small bills
• First aid kit
• Toiletries (toilet paper, soap, hand sanitizer etc.), 2 weeks’ worth
• Bucket toilet
• Garbage bags
• Personal hygiene items (toothbrush, toothpaste etc.)
• Medications, 2 weeks’ worth
• Face cover/mask, 14
• Medical equipment, 2 weeks’ worth
• Mobility devices
• Glasses/eye care
• Items for children (diapers, wipes, formula, toys etc.)
• Comfort/entertainment
• Copies of important documents (identification, insurance, financial accounts, family records, medical records, pictures etc.)
 
Vehicle Kit
• Water, 3 gallons
• Water filtration (filter, purification tablets)
• Food, 3 days’ worth
• Set of clothing
• Jacket
• Poncho
• Sturdy shoes
• Waterproof blanket
• Light source (flashlight, headlamp)
• Extra batteries
• NOAA Weather radio
• Phone charger
• Multi-tool with knife and can opener
• Duct tape
• Cash, small bills
• First aid kit
• Toiletries (toilet paper, soap, hand sanitizer etc.)
• Medications, 3 days’ worth
• Face cover/mask, 3
• Medical equipment, 3 days’ worth
• Glasses/eye care
• Items for children (diapers, wipes, formula, toys etc.)
• Comfort/entertainment
• Small shovel
• Jumper cables
• Road flare
 
Go Kit
• Water bottle
• Water filtration (filter, purification tablets)
• Food, 3 days’ worth
• Set of clothing
• Jacket
• Poncho
• Sturdy shoes
• Waterproof blanket
• Light source (flashlight, headlamp)
• Extra batteries
• NOAA Weather radio
• Phone charger
• Multi-tool with knife and can opener
• Duct tape
• Cash, small bills
• First aid kit
• Toiletries (toilet paper, soap, hand sanitizer etc.)
• Medications, 3 days’ worth
• Face cover/mask, 3
• Medical equipment, 3 days’ worth
• Glasses/eye care
• Items for children (diapers, wipes, formula, toys etc.)
• Comfort/entertainment
• Copies of important documents (insurance, financial accounts, family records, medical records, pictures etc.)
 
Work Kit
• Water, 3 gallons
• Water filtration (filter, purification tablets)
• Food, 3 days’ worth
• Set of clothing
• Jacket
• Poncho
• Sturdy shoes
• Waterproof blanket
• Light source (flashlight, headlamp)
• Extra batteries
• NOAA Weather radio
• Phone charger
• Multi-tool with knife and can opener
• Cash, small bills
• First aid kit
• Toiletries (toilet paper, soap, hand sanitizer etc.)
• Medications, 3 days’ worth
• Face cover/mask, 3
• Medical equipment, 3 days’ worth
• Glasses/eye care
• Comfort/entertainment
• Copies of important documents (insurance, financial accounts, family records, medical records, pictures etc.)
 
Pet Kit
• Leash or Harness
• Carrier
• Pet Food, 2 weeks’ worth
• Water, 2 weeks’ worth
• Food and water bowls, 2
• Pet waste management supplies (kitty litter, waste sanitation bags etc.)
• Blanket
• Towel
• Photo with family and pets
• Medication
• Medical records
• Toys
