### ISSUE TITLE
Hazard Hunt - Modeling

### ISSUE THREAD

**Issue by codingbandit** [HTBox/TwoWeeksReady#18]
Hazard Hunt deals is populated with recommendations of actions that can be taken now to avoid hazards in an emergency situation. These actions give the user ideas on what to add to the family plan in case of emergency (ie. turning off the gas/electric).

Hazard name, description, photo, directive should be provided. This list is not modifiable and is provided as an informational resource.

This module should share the same base functionality as Hazard information.

Update wiki with model information

For more details see the [wiki ](https://github.com/HTBox/TwoWeeksReady/wiki/Hazard-Hunt)

**Comment by schuback** [comment]
The recommended items list (hazard hunt) list is not modifiable by the end user.  We might add to it if we find items in the future during an update. Do we need to come up with the list for you?  @codingbandit

**Comment by codingbandit** [comment]
Modeling complete ![wiki](https://github.com/HTBox/TwoWeeksReady/wiki/Hazard-Hunt---Hazard-Information)
