### ISSUE TITLE
Am I correct in thinking that there are no Code Tours currently?

### ISSUE THREAD

**Issue by rfalanga** [HTBox/TwoWeeksReady#27]
Hello everyone, I've been looking over this project. Looking to see if this is a project that I'd like to contribute to. I learned of this project on both Dot Net Rocks and Runas Radio. (Hi @RichardCampbell!)

@codingbandit, I see that you've added a `ApiTour.tour` file to the project. Until I came across this, I'd never heard of CodeTour. I've installed the CodeTour VS Code extension. It looks to me that currently there are no tours yet. Am I correct?

**Comment by codingbandit** [comment]
Welcome @rfalanga ! Yes! we do have code tours. There is code tours for both UI and Api :) - find the UI code tours here: 2wr-app/code-tour/UITour.tour and the api code tours here: api/CodeTour/ApiTour.tour - if you open those in Visual Studio Code you can use your extension to go through the tours step by step ! Here is instructions on how to use the extension to get up to speed! https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour#starting-tours

**Comment by codingbandit** [comment]
You will also find readme documents in the root of both the UI and API folders with instructions on how to setup your environment

**Comment by rfalanga** [comment]
Thank you very much!
