### ISSUE TITLE
Hazard Hunt / Hazard Information - Functions Implementation

### ISSUE THREAD

**Issue by codingbandit** [HTBox/TwoWeeksReady#29]
See the [wiki information](https://github.com/HTBox/TwoWeeksReady/wiki/Hazard-Hunt---Hazard-Information) 

In the [API project](https://github.com/HTBox/TwoWeeksReady/tree/master/api)
- depending on if to common project is checked in - create base classes, and concrete classes as described in the modeling section
- create API for Hazard Hunt (get)
- create API for Hazard Information (get)
- you'll need to create a 2wr database in your Cosmos DB emulator, with two collections "hazardhunt" and "hazardinformation", there won't be too much data so you can partition on /id

**Comment by theancientcoder** [comment]
hi @codingbandit  I would happy to help with this

**Comment by steve-bate** [comment]
Hello @theancientcoder. Have you started working on this feature? I did some work on it (mostly to become familiar with the code base), but I don't want to submit a PR that will overlap with work you've already done.

**Comment by codingbandit** [comment]
Thank you @steve-bate for the PR :)
