### ISSUE TITLE
Hazard Hunt / Hazard Information - UI Implementation

### ISSUE THREAD

**Issue by codingbandit** [HTBox/TwoWeeksReady#30]
See the [wiki information](https://github.com/HTBox/TwoWeeksReady/wiki/Hazard-Hunt---Hazard-Information)

**Comment by steve-bate** [comment]
Questions:
1. Is there any content available for these views?
2. Do these views need authentication/login?

**Comment by codingbandit** [comment]
Hi @steve-bate - we currently don't have content for these views. They do not require authentication/login.

Examples of Hazard Information can be found here:
https://mil.wa.gov/hazards

Examples of Hazard Hunt could be:
Gas Shut Off - knowing where the gas shut off valve to the home is located, and how to operate it.
Secure furniture - bookshelves, curios, and other similar types of furniture can fall, secure them to the wall with brackets and straps.

@schuback - feel free to elaborate more here or add additional information to the wiki :)

**Comment by dpaquette** [comment]
Preliminary UI has been created. We will need to review the current state and fill in details here on what is work is remaining
