### ISSUE TITLE
Family Plan - Modeling

### ISSUE THREAD

**Issue by codingbandit** [HTBox/TwoWeeksReady#39]
https://mil.wa.gov/plan

@schuback  - we can discuss this at the 3/3 meeting, need to get details on how we see this working on the application.

**Comment by codingbandit** [comment]
@shawnwildermuth - I expect this task has been completed ? How do things stand with the Family Plan ? Thanks!

**Comment by shawnwildermuth** [comment]
We're about 2/3 complete. When I return from Wyoming (next week), i'll be able to dig into the actual showing of the plans. All the data modeling and data entry is complete.

**Comment by codingbandit** [comment]
Thank you so much @shawnwildermuth - very appreciated. Have safe travels!!
