### ISSUE TITLE
Signup is broken

### ISSUE THREAD

**Issue by acrigney** [HTBox/TwoWeeksReady#43]
I was trying to contact Richard Campbell but the signup page is broken.
I am interested in helping out with handling disasters like terror attacks and accident control/prevention.
I would also like to show you how I use Domain Driven Design.
I used to work for Transport. 
Please email me at acrigney@gmail.com

**Comment by codingbandit** [comment]
Hi @acrigney - welcome! Could you provide some additional information on this issue, is there an issue with the Auth0 registration of the application ?

**Comment by acrigney** [comment]
Thanks guys no this is just a sinple asp.net mc error. I will email you my
info.

**Comment by codingbandit** [comment]
@acrigney - are you talking about the admin web application ?

**Comment by codingbandit** [comment]
Closing due to no response. If you still require assistance, feel free to open a new issue.
