### ISSUE TITLE
GET api/emergencykits throwing 500 error

### ISSUE THREAD

**Issue by neelmallepally** [HTBox/TwoWeeksReady#55]
I have set up everything as described in the README files of each project(api, front end) and use CosmosEmulator tool to create cosmos db and collections in local CosmosDBEmulator. When I ran api project and used postman to run GET api/emergencykits end point, it is throwing 500 http status code. 

![image](https://user-images.githubusercontent.com/1775405/117686190-9f385280-b184-11eb-9e16-21405882a2e5.png)

Functions console log showing below error. 

![image](https://user-images.githubusercontent.com/1775405/117677177-377e0980-b17c-11eb-8c30-88dbb5aca462.png)

I changed `EnableCrossPartitionQuery = true` in `FeedOptions` of `CreateDocumentQuerymethod` like below and GET call worked as expected with 200 status code.

```
var query = client.CreateDocumentQuery<Kit>(collectionUri, new FeedOptions{EnableCrossPartitionQuery = true})
                                .Where(e => e.UserId == authorizationResult.User.Identity.Name)
                                .AsDocumentQuery();
```

Is it code issue in `api` or something I didn't set up correctly for my local cosmosDB collection instance?

**Comment by dpaquette** [comment]
It's possible your emergency kits collection has the wrong partition key defined.  Take a look at PR #53 that I just merged. It should initialize the collections correctly but you might need to delete your database and re-run the initializer

**Comment by neelmallepally** [comment]
PR #53 solved the issue I was having. Closing it.
