### ISSUE TITLE
Emergency Kit Create and Edit Forms Validation

### ISSUE THREAD

**Issue by neelmallepally** [HTBox/TwoWeeksReady#56]
Create and edit emergency kit forms allow user to save without entering "kit name", "Kit Item Name", "Description", "Quantity" etc.

![image](https://user-images.githubusercontent.com/1775405/117729262-9497b080-b1b8-11eb-9f59-399ff6005516.png)

![image](https://user-images.githubusercontent.com/1775405/117732155-5b157400-b1bd-11eb-8ca7-1337e729f5b1.png)

**Comment by neelmallepally** [comment]
@dpaquette @codingbandit - Is this a valid bug? If so, can I work on it? Thanks.

**Comment by dpaquette** [comment]
Yes, it is a valid bug. The UI for this feature be changing a bit but it would still be great to have validation in place for what's been built so far. Please feel free to work on it :-)
