### ISSUE TITLE
TEST Example - Broken image on signup page

### ISSUE THREAD

**Issue by schuback** [HTBox/TwoWeeksReady#61]
FYI - Working through issues process with Dante - this issue will be deleted / test purpose only
On an iphone 12. loaded app and HTBox logo on registration page was broken.  @ddisabat can you confirm new graphic to use from graphic library
![Screen Shot 2021-05-18 at 11 44 23 AM](https://user-images.githubusercontent.com/830036/119060277-ba763f80-b986-11eb-88ca-c6044d924224.png)

**Comment by DDisabat** [comment]
Thanks for the test. I will look into this/ TEST

**Comment by DDisabat** [comment]
Image file 456 has been uploaded in <>Code -> Assets -> Graphics 
link

**Comment by DDisabat** [comment]
@schuback this is ready for a developer to update
