### ISSUE TITLE
Admin Application - Implement Auth0 authentication

### ISSUE THREAD

**Issue by codingbandit** [HTBox/TwoWeeksReady#66]
Implement Auth0 authentication as to utilize the token to authenticate to the Function Apps in the middle tier.

**Comment by neelmallepally** [comment]
@codingbandit , is this issue reserved for any code hackathon live stream or open for anyone? I'm interested to take this if it is open to anyone? Thanks.

**Comment by codingbandit** [comment]
Hi Neil, this one is all yours :) thank you for contributing!

**Comment by neelmallepally** [comment]
@codingbandit @dpaquette I should have asked this question before starting my work on this issue. Please correct me if I'm going in the wrong direction for authentication/authorization in the admin app and in azure functions api. 

I'm following RBAC approach based on this recommendation from Auth0 - https://auth0.com/docs/authorization/rbac
- Define a role (let's say admin) : We will check if logged in user has this role or not when he/she will sign into the admin app. The reason I'm choosing a role is that if same login (SSO) is used for both 2wr-app (Vue) and 2wr-admin, we can control who is allowed to make changes in admin app by specifically assigning "admin" role to the logins via Auth0 dashboard. (I'm assuming we don't allow anyone to sign up through admin app?) 
- In the API, there are two choices.
   - In CUD operations, we can check if `ApiAuthenticationResult`'s user is in "admin" role or not and only allow CUD if it is admin.
   - Define permissions for API (ex: `write:basekits`, `write:hazardinfo`, `write:hazardhunt`) and these permissions will be assigned to "admin" role. Azure functions will check if the access token has policy `write:<resource_name>` in CUD operations. This option provides less code changes in the future if we want to add additional role in the application and they are limited to only specific resource operations. However, this requires some permissions set up in Auth0 Dashboard. Which option do you think is best for MVP? 

Thanks!

**Comment by dpaquette** [comment]
Thanks for your help with this @neelmallepally. I'm going to close this issue and create a new one to put some documentation in place (perhaps in a README for the Admin project) so folks know how to work on the admin app.
