### ISSUE TITLE
Feature: Save Buttons

### ISSUE THREAD

**Issue by DDisabat** [HTBox/TwoWeeksReady#73]
Make all save features in the application a button with the word "SAVE" written in it. This will replace the "floppy disk" save icon with buttons similar to the "WALKTHROUGH" and "MANAGE" buttons in the image below. 

![Save Button Style](https://user-images.githubusercontent.com/78102622/124182641-fc0d0680-da6b-11eb-9db2-8c22c60d5a0b.jpg)

Contact @MaximilianDixon @DDisabat for clarification if needed.

**Comment by marblekirby** [comment]
@DDisabat where does the new 'Save' button go on the page? should it go where the floppy disk currently is or should it be placed below the textbox like the 'Walkthrough' and 'Manage' buttons?

**Comment by DDisabat** [comment]
Hi @marblekirby looking at this again, the best solution is to actually replace the floppy disk and red "cancel" button with the edit pencil icon. When the edit pencil icon is clicked, it pops out a window to make edits and then on the bottom you can save your entry or cancel (this is how the other editable sections are within the family plan). So far, the floppy disk and cancel icon only appear to be on this part of the app.

**Comment by codingbandit** [comment]
Fixed, thank you @shawnwildermuth !
