### ISSUE TITLE
Bug: Exposed Coding in Family Plan

### ISSUE THREAD

**Issue by DDisabat** [HTBox/TwoWeeksReady#74]
When adding a child to the Family Plan, there is exposed coding shown at the bottom of the window. Please see screen recording for reference. 

Contact @DDisabat for further clarification if needed. 

https://user-images.githubusercontent.com/78102622/124184243-1fd14c00-da6e-11eb-82dd-db99a8202095.mp4

**Comment by dpaquette** [comment]
Looks like some local debugging code was accidentally checked in

**Comment by marblekirby** [comment]
PR merged, this issue can be resovled

**Comment by DDisabat** [comment]
Thank you so much for volunteering your time on this! I will go ahead and close the issue :)
