### ISSUE TITLE
Suggestion: Developer setup documentation

### ISSUE THREAD

**Issue by marblekirby** [HTBox/TwoWeeksReady#78]
This documentation may exist - I just cant find it! 

Can we get some setup docuemntation for this project (and if some exists can someone point me in the that direction or make it alot more visible?).

**As a** developer
**I want to** have instructions for application setup and configuration
**So that** I can get developing on this project quickly and without any errors

Acceptance Criteria: 
- Installations (what do i need to install?)
- Configuration (what do i need to configure?)
- Running (what do i need to run?)

**Comment by dpaquette** [comment]
Thanks @marblekirby 

We do have some documentation but as always it could probably use some improvement.  

There are 3 main parts to TwoWeeksReady. Each is in it's own folder in this repo and each of those folders has it's own README file which should have the info you need to get started.

1) api: The backend API built using Azure Functions, .NET Core and CosmosDB
2) 2wr-app: The Progress Web App built using VueJS and Vuetify
3) admin: An admin app for configuring data in the app built using Blazor.

You won't find much documentation on getting the Blazor app running. That part is still pretty new. The api and 2wr-app should have the information you need though,

Take a look and feel free to submit a PR with any improvements you can think of. It's always good to get a fresh new perspective on the docs.  One thing we could do is lay out the 3 different parts of the repo in the main README and link to the different folders.

I hope that helps!

**Comment by marblekirby** [comment]
Thanks. Let's try add that to the main Readme file so people can easily find it

**Comment by codingbandit** [comment]
Added links to project README docs on the main landing page in PR #81
